# simple translation of https://github.com/temporalio/docker-compose/blob/main/docker-compose.yml

databases:
- name: temporaltestdb
services:
- type: web
  name: temporaltestserver
  env: docker
  envVars:
  - key: DB
    value: postgresql
  - key: DB_PORT
    fromDatabase:
      name: temporaltestdb
      property: port
  - key: DBNAME
    value: temporaltestdb_fxcj # must hardcode because render adds a suffix to this thing
#     fromDatabase:
#       name: temporaltestdb
#       property: user
  - key: POSTGRES_USER
    fromDatabase:
      name: temporaltestdb
      property: user
  - key: POSTGRES_PWD
    fromDatabase:
      name: temporaltestdb
      property: password
  - key: POSTGRES_SEEDS
    fromDatabase:
      name: temporaltestdb
      property: host
  - key: DYNAMIC_CONFIG_FILE_PATH
    value: config/dynamicconfig/development_es.yaml
  - key: LOG_LEVEL
    value: debug,info
- type: web
  name: temporaltestweb
  env: docker
  dockerCommand: docker run temporalio/web:1.13.0
  envVars:
  - key: TEMPORAL_GRPC_ENDPOINT
#     value: temporal:7233
    fromService:
      name: temporaltestserver
      type: web
      property: hostport # this is a guess...
  - key: TEMPORAL_PERMIT_WRITE_API
    value: true
