services:
  - type: web
    autoDeploy: false
    name: temporal-ui
    env: docker
    dockerfilePath: ./temporal/ui/Dockerfile
    dockerContext: ./temporal/ui
    envVars:
      - key: TEMPORAL_GRPC_ENDPOINT
        value: temporal-frontend:7233
      # - key: TEMPORAL_CONFIG_PATH
      #   value: /etc/secrets/config.yml
  - type: worker
    autoDeploy: false
    name: temporal-admin-tools
    env: docker
    dockerfilePath: ./temporal/admin-tools/Dockerfile
    dockerContext: ./temporal/admin-tools
    envVars:
      - key: TEMPORAL_CLI_ADDRESS
        value: temporal-frontend:7233

databases:
  - name: temporal
    databaseName: temporal
    user: temporal
    plan: standard
